apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: reference-platform

resources:
  - ../../base

images:
  - name: reference-platform
    newName: ghcr.io/singhtanya05/reference-platform
    newTag: 7ac7dae44188e0b094b809679f73587b262fbfa1
