apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: reference-platform

resources:
  - ../../base

images:
  - name: reference-platform
    newName: ghcr.io/singhtanya05/reference-platform
    newTag: c505ed578df702fcb1fcdc12fda9896668479b21
