apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: reference-platform

resources:
  - ../../base

images:
  - name: reference-platform
    newName: ghcr.io/singhtanya05/reference-platform
    newTag: 5c931dbc4de536269835d7ffba6027a0633421e5
